media:
  input: public/uploads
  output: /uploads

content:
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    filename: '{year}{month}{day} - {primary}/post.mdx'
    view:
      fields: [title, publishDate, tags]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: publishDate
        label: Publish Date
        type: date
      - name: updatedDate
        label: Updated Date
        type: date
        required: false
      - name: tags
        label: Tags
        type: string
        list: true
        description: Use English tags, such as tech, photography, reading, film, thought.
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: comment
        label: Comment
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
